### ISSUE TITLE
2.5.0 is incompatible with configuration cache when extProperty setting is used

### ISSUE THREAD

**Issue by kdebski85** [n0mer/gradle-git-properties#241]
Gradle version: 8.13.
Plugin version: 2.5.0.

When `extProperty` setting is configured:
```
gitProperties {
    extProperty = 'gitProperties'
}
```

and project is built with displaying warnings:
`./gradlew build --warning-mode all`

The following warning is displayed:
```
> Task :generateGitProperties
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 10.0. This API is incompatible with the configuration cache, which will become the only mode supported by Gradle in a future release. Consult the upgrading guide for further information: https://docs.gradle.org/8.13/userguide/upgrading_version_7.html#task_project
```

---

Note:
I want to use `extProperty` to access the git commit id and write it to `application.yml`. Is there any better way to do it?
```
processResources {
    filesMatching('**application.yml') {
        filter {
            it.replace('last-commit-hash', project.ext.gitProperties['git.commit.id.abbrev'].toString())
        }
    }
}
```

**Comment by paul-kraftlauget** [comment]
I submitted a merge request to fix this within the plugin, but the README (and the code example for this issue) needs fixed too.

For example:
```
processResources {
    def ext = project.ext
    filesMatching('**application.yml') {
        filter {
            it.replace('last-commit-hash', ext.gitProperties['git.commit.id.abbrev'].toString())
        }
    }
}
```

In kotlin, I have done this:

```
// Expose all git properties to gradle runtime
gitProperties {
    extProperty = "gitProps" // git properties will be put in a map at project.ext["gitProps"]
}

// Always run task even if git.properties file is already generated as we want the properties in gradle
tasks.named<com.gorylenko.GenerateGitPropertiesTask>("generateGitProperties") {
    outputs.upToDateWhen { false }
}

// Make gradle properties available in application.yml and will be injected into ${...}
tasks.withType<ProcessResources> {
    dependsOn("generateGitProperties")
    val props = project.properties
    val ext = project.ext
    filesMatching("application-build-info.yml") {
        expand(props
                + mapOf("gitProps" to ext[gitProperties.extProperty])
                + mapOf(
                    "applicationName" to rootProject.name,
                    "containerImageName" to containerImageName,
                    "containerImageTag" to containerImageTag
                )
        )
    }
}
```


`application-build-info.yml`:

```
# injected during build
container:
  image:
    name: ${containerImageName}
    tag: ${containerImageTag}

# See generated git.properties file for possible keys
git:
  branch: ${gitProps["git.branch"]}
  commit:
    id: ${gitProps["git.commit.id"]}
    time: ${gitProps["git.commit.time"]}

spring:
  application:
    name: ${applicationName}
    version: ${version}
```
